name: my_app_3
description: "My App v3"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  path: ^1.9.0
  flutter_colorpicker: ^1.1.0
  intl: ^0.19.0
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  flutter_file_dialog: ^3.0.2
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
