name: my_app_3
description: "My App v3"
publish_to: 'none'
version: 3.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  flutter_colorpicker: ^1.1.0
  intl: ^0.20.1
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  flutter_file_dialog: ^3.0.2
  archive: ^4.0.1
  floor: ^1.5.0
  sqflite: ^2.4.0
  rxdart: ^0.28.0
  package_info_plus: ^8.1.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/sql/
